[project]
authors = [
  {"name" = "Franz Buchsbaum", "email" = "franz.buchsbaum@kununu.com"},
  {"name" = "Lorenzo Alfine", "email" = "lorenzo.alfine@kununu.com"},
]
description = "Can be used to convert mysql schema files to BigQuery schemas"
license = "MIT"
name = "mysql-to-bigquery-schema-converter"
readme = "README.md"
requires-python = ">=3.9,<3.15"
version = "1.2.0"

[project.scripts]
mysql-to-bigquery-schema-converter = "mysql_to_bigquery_schema_converter.cli:main"

[dependency-groups]
dev = [
  "ruff ~= 0.16",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
